steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us.gcr.io/$PROJECT_ID/angular-nginx-container', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us.gcr.io/$PROJECT_ID/angular-nginx-container']
  images: ['us.gcr.io/$PROJECT_ID/angular-nginx-container']
- name: gcr.io/cloud-builders/gcloud
- steps: ['app', 'deploy', '--image-url', 'us.gcr.io/$PROJECT_ID/angular-nginx-container']
options:
  logging: CLOUD_LOGGING_ONLY
